### ISSUE TITLE
Demo broken because of failing request/CORS

### ISSUE THREAD

**Issue by bbss** [vega/scalable-vega#119]
<img width="564" alt="Screen Shot 2022-04-01 at 9 10 23 AM" src="https://user-images.githubusercontent.com/2758664/161170613-1420b000-e08c-4a48-b759-b0a2e86bc080.png">

Both of the demoes seem to have this issue.

**Comment by domoritz** [comment]
Looks like omnisci/mapd/heavyai changed something about their servers. Do you know what the new domain may be?

**Comment by bbss** [comment]
I had a brief search around GitHub/the web but sadly can't find anything about it.

**Comment by domoritz** [comment]
https://metis.omnisci.com seems to be a thing.

**Comment by domoritz** [comment]
The server is up again. Thanks to Heavy.AI.

**Comment by bbss** [comment]
Thank you! 

FYI: I noticed you were already aware of this issue after searching a bit more. https://github.com/heavyai/metis/issues/131

**Comment by moklick** [comment]
👋 It seems to be broken again

**Comment by domoritz** [comment]
I get `net::ERR_CERT_DATE_INVALID`. @tmostak, can you help?

**Comment by ruuda** [comment]
I am now getting `net::ERR_CONNECTION_REFUSED` on a `POST https://metis.mapd.com/` request, and I get the same connection refused error if I just try to open https://metis.mapd.com/ in my browser.

**Comment by domoritz** [comment]
Looks like the server is down.

**Comment by domoritz** [comment]
@tmostak should we switch to another server?
