### ISSUE TITLE
What's the idea behind the scalability?

### ISSUE THREAD

**Issue by aerlaut** [vega/scalable-vega#136]
I see that the main work that was done to make Vega scalable was to precompute the data (i.e. move calculations into the backend) instead of doing it in transforms. Does this solution help if I need to visualize a large number of data points? (e.g. 500k dots)

**Comment by domoritz** [comment]
Thanks for asking. We are focusing on interactive scalability. If you want to show large datasets, I recommend using aggregation (as we do here) or the (experimental) WebGPU renderer: https://github.com/vega/vega-webgpu.
