### ISSUE TITLE
Broken demo due to invalid license

### ISSUE THREAD

**Issue by thinkh** [vega/scalable-vega#54]
1. [Open the demo](https://vega.github.io/scalable-vega/) -> nothing shows up
2. Open the developer console

![grafik](https://user-images.githubusercontent.com/5851088/86558935-fc5aea80-bf5a-11ea-86f6-2cf7f50c19e6.png)

```
Uncaught (in promise) 
window.TMapDException
error_msg: "License invalid"
__proto__: Error
```

**Comment by domoritz** [comment]
Hmm, odd. Maybe it’s a transient error with the mapd service.

**Comment by domoritz** [comment]
Looks like all MapD demos that rely on the instance are down right now. Closing in favor of https://github.com/omnisci/mapd-connector/issues/189
